services:
    cache_service_impl:
        class:        AppBundle\Service\Cache\RedisCacheService
        arguments:    [%cache_host%, %cache_port%, %cache_prefix%]
    database_service:
        class:        AppBundle\Service\DatabaseService
        arguments:    [%database_host%, %database_port%, %database_name%]
    cache_service:
        class:        AppBundle\Service\CacheService
        arguments:    [@cache_service_impl]
    customer_repository:
        class:        AppBundle\Repository\CustomerRepository
        arguments:    [@database_service]